name: test snapshot

on: push

jobs:
  test:
    name: run cache disk test
    runs-on: depot-ubuntu-latest
    steps:
      - uses: depot/cache-mount@v1
        with:
          path: /tmp/cache-mount
          name: test-disk
      - name: list cache
        run: |
          ls -la /tmp/cache-mount

      #- uses: depot/snapshot-action@v1
      #  env:
      #    REGISTRY_USERNAME: x-token
      #    REGISTRY_PASSWORD: $DEPOT_TOKEN
      #  with:
      #    image: p0tpj7swlt.registry.depot.dev/test:snapshot2
