name: test snapshot

on: push

jobs:
  benchmark:
    name: cache dependencies
    runs-on:
      image: p0tpj7swlt.registry.depot.dev/test:snapshot2
      size: 2x8
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          vim --version || true
          docker images

      # - uses: depot/snapshot-action@v1
      #   env:
      #     REGISTRY_USERNAME: x-token
      #     REGISTRY_PASSWORD: $DEPOT_TOKEN
      #   with:
      #     image: p0tpj7swlt.registry.depot.dev/test:snapshot2
